version: '3.0'
services:
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
    - "./data/pgadmin:/var/lib/pgadmin"
    depends_on:
    - bancodedados

  bancodedados:
    image: postgres:12.4
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
    - "./data/postgres:/var/lib/postgresql/data"
